query getProfile($id: String!) {
  profile(id: $id) {
    id
    email
  }
}
mutation signUp($input: UserInputSigUp!) {
  signUp(input: $input) {
    id
    email
    username
  }
}
mutation signIn($input: UserInputSigIn!) {
  signIn(input: $input) {
    id
    email
    username
    profilePicturer
    createdAt
  }
}
