query getProfile($id: String!) {
  profile(id: $id) {
    id
    email
  }
}
mutation signUp($input: UserInputSigUp!) {
  signUp(input: $input) {
    id
    email
    username
  }
}
mutation signIn($input: UserInputSigIn!) {
  signIn(input: $input) {
    id
    email
    username
    profilePicturer
    createdAt
  }
}
mutation Update($input: UserInputUpdate!, $profilePicturer: Upload!) {
  updade(input: $input, profilePicturer: $profilePicturer) {
    id
    password
    email
    updatedAt
  }
}
